version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: resourceDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-new:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  
      - "5672:5672"    
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres-data-new:
  rabbitmq-data: